cian/urls.py
from django.urls import path
from .views import (
    IndexView,
    ApartmentDetailView,
    ApartmentUpdateView,
    ImageDeleteView,
    ImageUpdateView,
    apartments_render_pdf_view,
    ProfileUpdateView,
    UserProfile,
    task_delete,
    apartment_delete,
)

app_name = "apartments"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("apartment/<int:pk>/delete", apartment_delete, name="delete"),
    path("image/<int:pk>/delete", ImageDeleteView.as_view(), name="delete-image"),
    path("apartment/<int:pk>/details", ApartmentDetailView.as_view(), name="apartment"),
    path("apartment/<int:pk>/update", ApartmentUpdateView.as_view(), name="update"),
    path("image/<int:pk>/update", ImageUpdateView.as_view(), name="update-image"),
    path(
        "apartment/<int:pk>/create_pdf", apartments_render_pdf_view, name="create_pdf"
    ),
    path("profile/", UserProfile.as_view(), name="profile"),
    path("task/<int:pk>", task_delete, name="task-delete"),
    path("<int:pk>/edit", ProfileUpdateView.as_view(), name="edit"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), # allauth urls
    path('', include('cian.urls', namespace='apartments')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cian/models.py
from django.db import models
from django.contrib.auth import get_user_model
from PIL import Image as Img

User = get_user_model()


class Apartment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    rooms = models.CharField("кол-во комнат", max_length=64, blank=True)
    price = models.CharField("цена", max_length=20, blank=True)
    address = models.CharField("Адрес", max_length=256, blank=True)
    desc = models.TextField("описание", blank=True)
    floor = models.CharField("этаж", max_length=10, blank=True)
    commission = models.CharField("коммисия", max_length=256, blank=True)

    def __str__(self):
        return self.address

    class Meta:
        verbose_name = "квартира"
        verbose_name_plural = "квартиры"


class Image(models.Model):
    apartment = models.ForeignKey(
        Apartment,
        on_delete=models.CASCADE,
        related_name="images",
        null=True,
        blank=True,
    )
    img = models.ImageField(upload_to="image/", blank=True)

    def save(self, *args, **kwargs):
        super().save()
        image = Img.open(self.img.path)
        cropped_image = image.crop((0, 0, 700, 650))  # лево, верх, право, низ
        cropped_image.save(self.img.path)

    class Meta:
        verbose_name = "фото"
        verbose_name_plural = "фото"


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField("Дата создания", auto_now_add=True)
    url = models.URLField("ссылка")

    def __str__(self):
        return self.url

    class Meta:
        verbose_name = "ссылка"
        verbose_name_plural = "ссылки"
        ordering = ["-created"]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField("имя", max_length=120, blank=True)
    last_name = models.CharField("фамилия", max_length=240, blank=True)
    phone_1 = models.CharField("телефон 1", max_length=18, blank=True)
    phone_2 = models.CharField("телефон 2", max_length=18, blank=True)
    avatar = models.ImageField(
        "аватар", default="avatars/avatar.png", upload_to="avatars/%Y/%m/%d"
    )
    email = models.EmailField("email")

    def __str__(self):
        return "Профиль пользователя %s" % self.user

    class Meta:
        verbose_name = "профиль"
        verbose_name_plural = "профили"

cian/forms.py
from django.forms import (
    ModelForm,
    URLInput,
    HiddenInput,
    FloatField,
    FileInput,
    Form,
    TextInput,
)
from .models import Apartment, Image, Profile
from PIL import Image as Img


class ButtonForm(Form):
    button = TextInput
    widgets = {
        "url": URLInput(
            attrs={
                "class": "form-control",
                "placeholder": "ссылка...",
            }
        ),
    }


class ApartmentEditForm(ModelForm):
    class Meta:
        model = Apartment
        fields = "__all__"


class ImageForm(ModelForm):
    x = FloatField(widget=HiddenInput())
    y = FloatField(widget=HiddenInput())
    width = FloatField(widget=HiddenInput())
    height = FloatField(widget=HiddenInput())

    class Meta:
        model = Image
        fields = (
            "img",
            "x",
            "y",
            "width",
            "height",
        )

        widgets = {
            FileInput(
                attrs={
                    "class": "form-control",
                }
            ),
        }

    # needed to crop a photo, override the method save
    def save(self):
        photo = super(ImageForm, self).save()

        x = self.cleaned_data.get("x")
        y = self.cleaned_data.get("y")
        w = self.cleaned_data.get("width")
        h = self.cleaned_data.get("height")

        image = Img.open(photo.img)  # Pillow
        cropped_image = image.crop((x, y, w + x, h + y))  # crop the image
        resized_image = cropped_image.resize(
            (400, 400), Img.ANTIALIAS
        )  # resize cropped image
        resized_image.save(photo.img.path)  # save resized image

        return resized_image


class ProfileEditForm(ModelForm):
    class Meta:
        model = Profile
        fields = ("avatar", "first_name", "last_name", "email", "phone_1", "phone_2")

cian/views.py
import os
from io import BytesIO
from threading import Thread

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView, UpdateView
from django.contrib.auth.decorators import login_required
from xhtml2pdf import pisa

from .forms import ApartmentEditForm, ImageForm, ProfileEditForm
from .models import Apartment, Image, Task, Profile
from .scraper import save_data, get_page_data


class IndexView(LoginRequiredMixin, ListView):
    model = Apartment
    template_name = "cian/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["apartments_list"] = Apartment.objects.filter(owner=self.request.user)
        context["profile"] = Profile.objects.get(user=self.request.user)
        return context


class ApartmentDetailView(LoginRequiredMixin, DetailView):
    model = Apartment
    template_name = "cian/apartment.html"
    context_object_name = "apartments"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profile"] = Profile.objects.get(user=self.request.user)
        return context


# class ApartmentDeleteView(LoginRequiredMixin, DeleteView):
#     model = Apartment
#     templates = 'cian/apartment_confirm_delete.html'
#     success_url = reverse_lazy('apartments:profile')
#
#     def get_context_data(self, *args, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['profile'] = Profile.objects.get(user=self.request.user)
#         return context


class ImageDeleteView(LoginRequiredMixin, DeleteView):
    model = Image
    # templates = 'cian/image_confirm_delete.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profile"] = Profile.objects.get(user=self.request.user)
        return context

    def get_success_url(self):
        return reverse_lazy(
            "apartments:apartment", kwargs={"pk": self.object.apartment.pk}
        )


class ApartmentUpdateView(LoginRequiredMixin, UpdateView):
    model = Apartment
    form_class = ApartmentEditForm
    template_name = "cian/apartment_update.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profile"] = Profile.objects.get(user=self.request.user)
        return context

    def get_success_url(self):
        return reverse_lazy("apartments:apartment", kwargs={"pk": self.object.pk})


class ImageUpdateView(LoginRequiredMixin, UpdateView):
    model = Image
    form_class = ImageForm
    success_url = reverse_lazy("apartments:profile")
    template_name = "cian/image_update.html"
    context_object_name = "image"


class UserProfile(LoginRequiredMixin, ListView):
    model = Profile
    template_name = "cian/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profile"] = Profile.objects.get(user=self.request.user)
        context["tasks"] = Task.objects.filter(user=self.request.user)
        context["apartments_list"] = Apartment.objects.filter(owner=self.request.user)
        return context

    def post(self, request):
        user = self.request.user
        if self.request.POST.get("form_type") == "form_1":
            url = request.POST["url"]
            t = Task(url=url, user=user)
            t.save()
            return redirect("apartments:profile")

        elif self.request.POST.get("form_type") == "form_2":
            qs = Task.objects.filter(user=user)
            for url in qs:
                apartments = get_page_data(url)
                save_items = Thread(
                    target=save_data,
                    args=(
                        apartments,
                        user,
                    ),
                )
                save_items.start()
            return redirect("apartments:profile")


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = ProfileEditForm
    template_name = "cian/edit.html"
    success_url = reverse_lazy("apartments:profile")


def fetch_pdf_resources(uri, rel):
    """
    Convert HTML URIs to absolute system paths so xhtml2pdf can access those
    resources
    """
    # use short variable names
    sUrl = settings.STATIC_URL  # Typically /static/
    sRoot = settings.STATIC_ROOT  # Typically /home/userX/project_static/
    mUrl = settings.MEDIA_URL  # Typically /static/media/
    mRoot = settings.MEDIA_ROOT  # Typically /home/userX/project_static/media/

    # convert URIs to absolute system paths
    if uri.startswith(mUrl):
        path = os.path.join(mRoot, uri.replace(mUrl, ""))
    elif uri.startswith(sUrl):
        path = os.path.join(sRoot, uri.replace(sUrl, ""))
    else:
        return uri  # handle absolute uri (ie: http://some.tld/foo.png)

    # make sure that file exists
    if not os.path.isfile(path):
        raise Exception("media URI must start with %s or %s" % (sUrl, mUrl))
    return path


@login_required
def apartments_render_pdf_view(request, *args, **kwargs):
    pk = kwargs.get("pk")
    apartment = get_object_or_404(Apartment, pk=pk)
    user = Profile.objects.get(user=request.user.id)

    template_path = "cian/report.html"
    context = {
        "apartment": apartment,
        "user": user,
    }
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)
    result = BytesIO()
    # create a pdf
    pdf = pisa.pisaDocument(
        BytesIO(html.encode("UTF-8")),
        result,
        encoding="UTF-8",
        link_callback=fetch_pdf_resources,
    )
    apartment.delete()  # remove object after file creation
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type="application/pdf")

    return None


@login_required
def task_delete(request, pk):
    task = Task.objects.get(id=pk)
    task.delete()
    return redirect(reverse_lazy("apartments:profile"))


@login_required
def apartment_delete(request, pk):
    apartment = Apartment.objects.get(id=pk)
    apartment.delete()
    return redirect(reverse_lazy("apartments:profile"))

cian/templates/cian/apartment.html
{% extends 'base.html' %} {% block content %} {% if user.is_authenticated %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      {% for img in apartments.images.all %}
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img src="{{ img.img.url }}" width="100%" height="350" alt="" />
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a type="button" href="{% url 'apartments:update-image' img.pk %}"
                  class="btn btn-sm btn-outline-primary">Редактировать</a>
                <a type="button" class="btn btn-sm btn-outline-danger"
                  href="{% url 'apartments:delete-image' img.pk %}">Удалить</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <hr />
    <h5 class="card-title">{{ apartments.address }}</h5>
    <h5 class="card-title">{{ apartments.rooms }}</h5>
    <h5 class="card-title">{{ apartments.floor }}</h5>
    <h5 class="card-title">{{ apartments.price }}</h5>
    <h5 class="card-title">{{ apartments.commission }}</h5>
    <p class="card-text">{{ apartments.desc }}</p>
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        <a type="button" class="btn btn-sm btn-outline-primary" href="{% url 'apartments:update' apartments.pk %}">
          Редактировать
        </a>
        <a class="btn btn-sm btn-outline-danger" href="{% url 'apartments:delete' apartments.pk %}">
          Удалить
        </a>
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'apartments:create_pdf' apartments.pk %}"
          target="_blank">
          создать PDF
        </a>
      </div>
    </div>
  </div>
  {% else %}
  <p>Вы не авторизованы!</p>
  {% endif %}
</div>
{% endblock content %}

cian/templates/cian/apartment_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<br>
<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto"></div>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <hr>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
</div>
{% endblock content %}

cian/templates/cian/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

{% if user.is_authenticated %}
<br>
<div class="container">
<div class="row">
    <div class="col-6">
    <h2>изменить профиль пользователя {{ user }}</h2>
    <br>
    <p>Используйте форму ниже чтобы что-то поменять в профиле:</p>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
      <button class="btn btn-outline-dark" type="submit">Сохранить</button>
    </form>
    </div>
</div>
    </div>
<br>
{% endif %}
{% endblock %}

cian/templates/cian/image_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="col-lg-8 col-md-10 mx-auto"></div>
    <h2>Действительно удалить?</h2>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn-sm btn btn-danger">Удалить</button>
    </form>
</div>
</div>
{% endblock %}

cian/templates/cian/index.html
{% extends 'base.html' %} {% block content %} {% if user.is_authenticated %}
{% for apartment in apartments_list %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      {% for img in apartment.images.all %}
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img src="{{ img.img.url }}" width="100%" height="350" alt="" />
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a type="button" href="{% url 'apartments:update-image' img.pk %}"
                  class="btn btn-sm btn-outline-primary">Редактировать</a>
                <a type="button" class="btn btn-sm btn-outline-danger"
                  href="{% url 'apartments:delete-image' img.pk %}">Удалить</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <hr />
    <h5 class="card-title">{{ apartment.address }}</h5>
    <h5 class="card-title">{{ apartment.rooms }}</h5>
    <h5 class="card-title">{{ apartment.floor }}</h5>
    <h5 class="card-title">{{ apartment.price }}</h5>
    <h5 class="card-title">{{ apartment.commission }}</h5>
    <p class="card-text">{{ apartment.desc }}</p>
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        <a type="button" class="btn btn-sm btn-outline-primary" href="{% url 'apartments:update' apartment.id %}">
          Редактировать
        </a>
        <a class="btn btn-sm btn-outline-danger" href="{% url 'apartments:delete' apartment.id %}">
          Удалить
        </a>
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'apartments:create_pdf' apartment.pk %}"
          target="_blank">
          создать PDF
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p>Вы не авторизованы!</p>
  {% endif %}
</div>
{% endblock content %}

cian/templates/cian/profile.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
<br>
<br>
<div class="container">
    <div class="main-body">
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{ profile.avatar.url }}" alt="admin" width="300" class="">
                    <div class="mt-3">
                      <h4>{{ profile.first_name }} {{ profile.last_name }}</h4>
                      <!-- <p class="text-secondary mb-1">Full Stack Developer</p>
                      <p class="text-muted font-size-sm">Bay Area, San Francisco, CA</p>
                      <button class="btn btn-primary">Follow</button>
                      <button class="btn btn-outline-primary">Message</button> -->
                    </div>
                  </div>
                </div>
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <div class="mt-3">
                      <form id="form_1" action="." method="post">
                        {% csrf_token %}
                        <input type="url" class="form-control" name="url" placeholder="ссылка...">
                        <input type="hidden" name="form_type" value="form_1" />
                        <button class="btn btn-primary mb-2" type="submit">+</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  {% for task in tasks %}
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <!-- <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg></h6> -->
                    <a class="remove-task" href="{% url 'apartments:task-delete' task.pk %}">X</a>
                    <span class="text-secondary">{{ task.url }}</span>
                  </li>
                  {% endfor %}
                  <!-- <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github mr-2 icon-inline"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>Github</h6>
                    <span class="text-secondary">bootdey</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                    <span class="text-secondary">@bootdey</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                    <span class="text-secondary">bootdey</span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
                    <span class="text-secondary">bootdey</span>
                  </li> -->
                </ul>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Полное имя</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ profile.first_name }} {{ profile.last_name }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ profile.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Телефон 1</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ profile.phone_1 }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Телефон 2</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ profile.phone_2 }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                   <!-- <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      Bay Area, San Francisco, CA
                    </div> -->
                  </div>
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn btn-sm btn-outline-primary" target="__blank" href="{% url 'apartments:edit' profile.pk %}">Редактировать</a>
                    </div>
                  </div>
                </div>
              </div>
              <form id="form_2" action="." method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-sm btn-outline-primary" value="Получить данные">
                <input type="hidden" name="form_type" value="form_2" />
              </form>
              <hr>
              <div class="row gutters-sm">
                {% for apartment in apartments_list %}
                <div class="col-sm-6 mb-3">
                  {#% for img in apartment.images.all %#}
                  <div class="card h-100">
                    <!-- <img src="{#{ img.img.url}#}" width="100%" height="350" alt="" /> -->
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3">{{ apartment.address }}</h6>
                      <div class="card-text">
                        Количество комнат: {{ apartment.rooms }}
                      </div>
                      <br>
                      <div class="card-text">
                        Цена: {{ apartment.price }}₽
                      </div>
                      <br>
                      <div class="card-text">
                        Этаж: {{ apartment.floor }}
                      </div>
                      <div class="card-text">
                        Коммисия: {{ apartment.commission }}
                      </div>
                      <hr>
                      <div class="card-text">
                        {{ apartment.desc|truncatewords:30 }}
                      </div>
                      <hr>
                      <a class="btn btn-sm btn-outline-primary float-right" href="{% url 'apartments:apartment' apartment.pk %}">Просмотр</a>
                    </div>
                  </div>
                  {#% endfor %#}
                </div>
                <!--<div class="col-sm-6 mb-3">
                  <div class="card h-100">
                    <div class="card-body">
                      <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                      <small>Web Design</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Website Markup</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>One Page</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Mobile Template</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                      <small>Backend API</small>
                      <div class="progress mb-3" style="height: 5px">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                  </div>
                </div> -->
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
{% endif %}
{% endblock content %}