cian/urls.py
from django.urls import path
from .views import (
    IndexView,
    ApartmentDetailView,
    ApartmentUpdateView,
    ImageDeleteView,
    ImageUpdateView,
    apartments_render_pdf_view,
    ProfileUpdateView,
    UserProfile,
    task_delete,
    apartment_delete,
)

app_name = "apartments"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("apartment/<int:pk>/delete", apartment_delete, name="delete"),
    path("image/<int:pk>/delete", ImageDeleteView.as_view(), name="delete-image"),
    path("apartment/<int:pk>/details", ApartmentDetailView.as_view(), name="apartment"),
    path("apartment/<int:pk>/update", ApartmentUpdateView.as_view(), name="update"),
    path("image/<int:pk>/update", ImageUpdateView.as_view(), name="update-image"),
    path(
        "apartment/<int:pk>/create_pdf", apartments_render_pdf_view, name="create_pdf"
    ),
    path("profile/", UserProfile.as_view(), name="profile"),
    path("task/<int:pk>", task_delete, name="task-delete"),
    path("<int:pk>/edit", ProfileUpdateView.as_view(), name="edit"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), # allauth urls
    path('', include('cian.urls', namespace='apartments')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <!-- Required meta tags -->
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  {% load static %}
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <link href="{% static 'css/cropper.css' %}" rel="stylesheet" />
  <title>Циан парсер</title>
  {% block style %}{% endblock style %}
</head>

<body>
  {% if user.is_authenticated %}
  <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'apartments:profile' %}">
      <img src="{{ profile.avatar.url }}" width="30" height="30" class="d-inline-block align-top" alt="">
    </a>
    <a class="navbar-brand" href="{% url 'account_logout' %}">Выйти</a>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'apartments:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
  </nav>
  {% else %}
  <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'account_login' %}">Войти</a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'account_signup' %}">Зарегистрироваться <span
              class="sr-only">(current)</span></a>
        </li>
      </ul>
    </div>
  </nav>
  {% endif %}
  {% block content %} {% endblock content %}
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/cropper.js' %}"></script>
  {% block javascript %} {% endblock %}
</body>

</html>